/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KuendigenRouteImport } from './routes/kuendigen'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as EmailBestaetigtRouteImport } from './routes/email-bestaetigt'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AvvRouteImport } from './routes/avv'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardPreiseRouteImport } from './routes/dashboard.preise'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard.portfolio'
import { Route as DashboardMieterportalRouteImport } from './routes/dashboard.mieterportal'
import { Route as DashboardMietanpassungRouteImport } from './routes/dashboard.mietanpassung'
import { Route as DashboardMaengelRouteImport } from './routes/dashboard.maengel'
import { Route as DashboardHandwerkerRouteImport } from './routes/dashboard.handwerker'
import { Route as DashboardFinanzierungRouteImport } from './routes/dashboard.finanzierung'
import { Route as DashboardDokumenteRouteImport } from './routes/dashboard.dokumente'
import { Route as DashboardAufgabenRouteImport } from './routes/dashboard.aufgaben'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as DashboardUebergabeIndexRouteImport } from './routes/dashboard.uebergabe.index'
import { Route as DashboardObjekteIndexRouteImport } from './routes/dashboard.objekte.index'
import { Route as DashboardNebenkostenIndexRouteImport } from './routes/dashboard.nebenkosten.index'
import { Route as DashboardMieteIndexRouteImport } from './routes/dashboard.miete.index'
import { Route as DashboardDokumenteIndexRouteImport } from './routes/dashboard.dokumente.index'
import { Route as DashboardUebergabeIdRouteImport } from './routes/dashboard.uebergabe.$id'
import { Route as DashboardObjekteIdRouteImport } from './routes/dashboard.objekte.$id'
import { Route as DashboardNebenkostenIdRouteImport } from './routes/dashboard.nebenkosten.$id'
import { Route as DashboardMieteEingaengeRouteImport } from './routes/dashboard.miete.eingaenge'
import { Route as DashboardDokumenteObjektIdRouteImport } from './routes/dashboard.dokumente.$objektId'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KuendigenRoute = KuendigenRouteImport.update({
  id: '/kuendigen',
  path: '/kuendigen',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailBestaetigtRoute = EmailBestaetigtRouteImport.update({
  id: '/email-bestaetigt',
  path: '/email-bestaetigt',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AvvRoute = AvvRouteImport.update({
  id: '/avv',
  path: '/avv',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPreiseRoute = DashboardPreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMieterportalRoute = DashboardMieterportalRouteImport.update({
  id: '/mieterportal',
  path: '/mieterportal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMietanpassungRoute = DashboardMietanpassungRouteImport.update({
  id: '/mietanpassung',
  path: '/mietanpassung',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMaengelRoute = DashboardMaengelRouteImport.update({
  id: '/maengel',
  path: '/maengel',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHandwerkerRoute = DashboardHandwerkerRouteImport.update({
  id: '/handwerker',
  path: '/handwerker',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanzierungRoute = DashboardFinanzierungRouteImport.update({
  id: '/finanzierung',
  path: '/finanzierung',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDokumenteRoute = DashboardDokumenteRouteImport.update({
  id: '/dokumente',
  path: '/dokumente',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAufgabenRoute = DashboardAufgabenRouteImport.update({
  id: '/aufgaben',
  path: '/aufgaben',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUebergabeIndexRoute = DashboardUebergabeIndexRouteImport.update({
  id: '/uebergabe/',
  path: '/uebergabe/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardObjekteIndexRoute = DashboardObjekteIndexRouteImport.update({
  id: '/objekte/',
  path: '/objekte/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNebenkostenIndexRoute =
  DashboardNebenkostenIndexRouteImport.update({
    id: '/nebenkosten/',
    path: '/nebenkosten/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMieteIndexRoute = DashboardMieteIndexRouteImport.update({
  id: '/miete/',
  path: '/miete/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDokumenteIndexRoute = DashboardDokumenteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDokumenteRoute,
} as any)
const DashboardUebergabeIdRoute = DashboardUebergabeIdRouteImport.update({
  id: '/uebergabe/$id',
  path: '/uebergabe/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardObjekteIdRoute = DashboardObjekteIdRouteImport.update({
  id: '/objekte/$id',
  path: '/objekte/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNebenkostenIdRoute = DashboardNebenkostenIdRouteImport.update({
  id: '/nebenkosten/$id',
  path: '/nebenkosten/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMieteEingaengeRoute = DashboardMieteEingaengeRouteImport.update({
  id: '/miete/eingaenge',
  path: '/miete/eingaenge',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDokumenteObjektIdRoute =
  DashboardDokumenteObjektIdRouteImport.update({
    id: '/$objektId',
    path: '/$objektId',
    getParentRoute: () => DashboardDokumenteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/avv': typeof AvvRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/email-bestaetigt': typeof EmailBestaetigtRoute
  '/impressum': typeof ImpressumRoute
  '/kuendigen': typeof KuendigenRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/aufgaben': typeof DashboardAufgabenRoute
  '/dashboard/dokumente': typeof DashboardDokumenteRouteWithChildren
  '/dashboard/finanzierung': typeof DashboardFinanzierungRoute
  '/dashboard/handwerker': typeof DashboardHandwerkerRoute
  '/dashboard/maengel': typeof DashboardMaengelRoute
  '/dashboard/mietanpassung': typeof DashboardMietanpassungRoute
  '/dashboard/mieterportal': typeof DashboardMieterportalRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/preise': typeof DashboardPreiseRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/dokumente/$objektId': typeof DashboardDokumenteObjektIdRoute
  '/dashboard/miete/eingaenge': typeof DashboardMieteEingaengeRoute
  '/dashboard/nebenkosten/$id': typeof DashboardNebenkostenIdRoute
  '/dashboard/objekte/$id': typeof DashboardObjekteIdRoute
  '/dashboard/uebergabe/$id': typeof DashboardUebergabeIdRoute
  '/dashboard/dokumente/': typeof DashboardDokumenteIndexRoute
  '/dashboard/miete/': typeof DashboardMieteIndexRoute
  '/dashboard/nebenkosten/': typeof DashboardNebenkostenIndexRoute
  '/dashboard/objekte/': typeof DashboardObjekteIndexRoute
  '/dashboard/uebergabe/': typeof DashboardUebergabeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/avv': typeof AvvRoute
  '/datenschutz': typeof DatenschutzRoute
  '/email-bestaetigt': typeof EmailBestaetigtRoute
  '/impressum': typeof ImpressumRoute
  '/kuendigen': typeof KuendigenRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/aufgaben': typeof DashboardAufgabenRoute
  '/dashboard/finanzierung': typeof DashboardFinanzierungRoute
  '/dashboard/handwerker': typeof DashboardHandwerkerRoute
  '/dashboard/maengel': typeof DashboardMaengelRoute
  '/dashboard/mietanpassung': typeof DashboardMietanpassungRoute
  '/dashboard/mieterportal': typeof DashboardMieterportalRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/preise': typeof DashboardPreiseRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/dokumente/$objektId': typeof DashboardDokumenteObjektIdRoute
  '/dashboard/miete/eingaenge': typeof DashboardMieteEingaengeRoute
  '/dashboard/nebenkosten/$id': typeof DashboardNebenkostenIdRoute
  '/dashboard/objekte/$id': typeof DashboardObjekteIdRoute
  '/dashboard/uebergabe/$id': typeof DashboardUebergabeIdRoute
  '/dashboard/dokumente': typeof DashboardDokumenteIndexRoute
  '/dashboard/miete': typeof DashboardMieteIndexRoute
  '/dashboard/nebenkosten': typeof DashboardNebenkostenIndexRoute
  '/dashboard/objekte': typeof DashboardObjekteIndexRoute
  '/dashboard/uebergabe': typeof DashboardUebergabeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/avv': typeof AvvRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/email-bestaetigt': typeof EmailBestaetigtRoute
  '/impressum': typeof ImpressumRoute
  '/kuendigen': typeof KuendigenRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/aufgaben': typeof DashboardAufgabenRoute
  '/dashboard/dokumente': typeof DashboardDokumenteRouteWithChildren
  '/dashboard/finanzierung': typeof DashboardFinanzierungRoute
  '/dashboard/handwerker': typeof DashboardHandwerkerRoute
  '/dashboard/maengel': typeof DashboardMaengelRoute
  '/dashboard/mietanpassung': typeof DashboardMietanpassungRoute
  '/dashboard/mieterportal': typeof DashboardMieterportalRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/preise': typeof DashboardPreiseRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/dokumente/$objektId': typeof DashboardDokumenteObjektIdRoute
  '/dashboard/miete/eingaenge': typeof DashboardMieteEingaengeRoute
  '/dashboard/nebenkosten/$id': typeof DashboardNebenkostenIdRoute
  '/dashboard/objekte/$id': typeof DashboardObjekteIdRoute
  '/dashboard/uebergabe/$id': typeof DashboardUebergabeIdRoute
  '/dashboard/dokumente/': typeof DashboardDokumenteIndexRoute
  '/dashboard/miete/': typeof DashboardMieteIndexRoute
  '/dashboard/nebenkosten/': typeof DashboardNebenkostenIndexRoute
  '/dashboard/objekte/': typeof DashboardObjekteIndexRoute
  '/dashboard/uebergabe/': typeof DashboardUebergabeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/avv'
    | '/dashboard'
    | '/datenschutz'
    | '/email-bestaetigt'
    | '/impressum'
    | '/kuendigen'
    | '/login'
    | '/portal'
    | '/dashboard/account'
    | '/dashboard/aufgaben'
    | '/dashboard/dokumente'
    | '/dashboard/finanzierung'
    | '/dashboard/handwerker'
    | '/dashboard/maengel'
    | '/dashboard/mietanpassung'
    | '/dashboard/mieterportal'
    | '/dashboard/portfolio'
    | '/dashboard/preise'
    | '/dashboard/'
    | '/dashboard/dokumente/$objektId'
    | '/dashboard/miete/eingaenge'
    | '/dashboard/nebenkosten/$id'
    | '/dashboard/objekte/$id'
    | '/dashboard/uebergabe/$id'
    | '/dashboard/dokumente/'
    | '/dashboard/miete/'
    | '/dashboard/nebenkosten/'
    | '/dashboard/objekte/'
    | '/dashboard/uebergabe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/avv'
    | '/datenschutz'
    | '/email-bestaetigt'
    | '/impressum'
    | '/kuendigen'
    | '/login'
    | '/portal'
    | '/dashboard/account'
    | '/dashboard/aufgaben'
    | '/dashboard/finanzierung'
    | '/dashboard/handwerker'
    | '/dashboard/maengel'
    | '/dashboard/mietanpassung'
    | '/dashboard/mieterportal'
    | '/dashboard/portfolio'
    | '/dashboard/preise'
    | '/dashboard'
    | '/dashboard/dokumente/$objektId'
    | '/dashboard/miete/eingaenge'
    | '/dashboard/nebenkosten/$id'
    | '/dashboard/objekte/$id'
    | '/dashboard/uebergabe/$id'
    | '/dashboard/dokumente'
    | '/dashboard/miete'
    | '/dashboard/nebenkosten'
    | '/dashboard/objekte'
    | '/dashboard/uebergabe'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/avv'
    | '/dashboard'
    | '/datenschutz'
    | '/email-bestaetigt'
    | '/impressum'
    | '/kuendigen'
    | '/login'
    | '/portal'
    | '/dashboard/account'
    | '/dashboard/aufgaben'
    | '/dashboard/dokumente'
    | '/dashboard/finanzierung'
    | '/dashboard/handwerker'
    | '/dashboard/maengel'
    | '/dashboard/mietanpassung'
    | '/dashboard/mieterportal'
    | '/dashboard/portfolio'
    | '/dashboard/preise'
    | '/dashboard/'
    | '/dashboard/dokumente/$objektId'
    | '/dashboard/miete/eingaenge'
    | '/dashboard/nebenkosten/$id'
    | '/dashboard/objekte/$id'
    | '/dashboard/uebergabe/$id'
    | '/dashboard/dokumente/'
    | '/dashboard/miete/'
    | '/dashboard/nebenkosten/'
    | '/dashboard/objekte/'
    | '/dashboard/uebergabe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  AvvRoute: typeof AvvRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DatenschutzRoute: typeof DatenschutzRoute
  EmailBestaetigtRoute: typeof EmailBestaetigtRoute
  ImpressumRoute: typeof ImpressumRoute
  KuendigenRoute: typeof KuendigenRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuendigen': {
      id: '/kuendigen'
      path: '/kuendigen'
      fullPath: '/kuendigen'
      preLoaderRoute: typeof KuendigenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-bestaetigt': {
      id: '/email-bestaetigt'
      path: '/email-bestaetigt'
      fullPath: '/email-bestaetigt'
      preLoaderRoute: typeof EmailBestaetigtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avv': {
      id: '/avv'
      path: '/avv'
      fullPath: '/avv'
      preLoaderRoute: typeof AvvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preise': {
      id: '/dashboard/preise'
      path: '/preise'
      fullPath: '/dashboard/preise'
      preLoaderRoute: typeof DashboardPreiseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mieterportal': {
      id: '/dashboard/mieterportal'
      path: '/mieterportal'
      fullPath: '/dashboard/mieterportal'
      preLoaderRoute: typeof DashboardMieterportalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mietanpassung': {
      id: '/dashboard/mietanpassung'
      path: '/mietanpassung'
      fullPath: '/dashboard/mietanpassung'
      preLoaderRoute: typeof DashboardMietanpassungRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/maengel': {
      id: '/dashboard/maengel'
      path: '/maengel'
      fullPath: '/dashboard/maengel'
      preLoaderRoute: typeof DashboardMaengelRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/handwerker': {
      id: '/dashboard/handwerker'
      path: '/handwerker'
      fullPath: '/dashboard/handwerker'
      preLoaderRoute: typeof DashboardHandwerkerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/finanzierung': {
      id: '/dashboard/finanzierung'
      path: '/finanzierung'
      fullPath: '/dashboard/finanzierung'
      preLoaderRoute: typeof DashboardFinanzierungRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dokumente': {
      id: '/dashboard/dokumente'
      path: '/dokumente'
      fullPath: '/dashboard/dokumente'
      preLoaderRoute: typeof DashboardDokumenteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/aufgaben': {
      id: '/dashboard/aufgaben'
      path: '/aufgaben'
      fullPath: '/dashboard/aufgaben'
      preLoaderRoute: typeof DashboardAufgabenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/uebergabe/': {
      id: '/dashboard/uebergabe/'
      path: '/uebergabe'
      fullPath: '/dashboard/uebergabe/'
      preLoaderRoute: typeof DashboardUebergabeIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/objekte/': {
      id: '/dashboard/objekte/'
      path: '/objekte'
      fullPath: '/dashboard/objekte/'
      preLoaderRoute: typeof DashboardObjekteIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/nebenkosten/': {
      id: '/dashboard/nebenkosten/'
      path: '/nebenkosten'
      fullPath: '/dashboard/nebenkosten/'
      preLoaderRoute: typeof DashboardNebenkostenIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/miete/': {
      id: '/dashboard/miete/'
      path: '/miete'
      fullPath: '/dashboard/miete/'
      preLoaderRoute: typeof DashboardMieteIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dokumente/': {
      id: '/dashboard/dokumente/'
      path: '/'
      fullPath: '/dashboard/dokumente/'
      preLoaderRoute: typeof DashboardDokumenteIndexRouteImport
      parentRoute: typeof DashboardDokumenteRoute
    }
    '/dashboard/uebergabe/$id': {
      id: '/dashboard/uebergabe/$id'
      path: '/uebergabe/$id'
      fullPath: '/dashboard/uebergabe/$id'
      preLoaderRoute: typeof DashboardUebergabeIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/objekte/$id': {
      id: '/dashboard/objekte/$id'
      path: '/objekte/$id'
      fullPath: '/dashboard/objekte/$id'
      preLoaderRoute: typeof DashboardObjekteIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/nebenkosten/$id': {
      id: '/dashboard/nebenkosten/$id'
      path: '/nebenkosten/$id'
      fullPath: '/dashboard/nebenkosten/$id'
      preLoaderRoute: typeof DashboardNebenkostenIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/miete/eingaenge': {
      id: '/dashboard/miete/eingaenge'
      path: '/miete/eingaenge'
      fullPath: '/dashboard/miete/eingaenge'
      preLoaderRoute: typeof DashboardMieteEingaengeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dokumente/$objektId': {
      id: '/dashboard/dokumente/$objektId'
      path: '/$objektId'
      fullPath: '/dashboard/dokumente/$objektId'
      preLoaderRoute: typeof DashboardDokumenteObjektIdRouteImport
      parentRoute: typeof DashboardDokumenteRoute
    }
  }
}

interface DashboardDokumenteRouteChildren {
  DashboardDokumenteObjektIdRoute: typeof DashboardDokumenteObjektIdRoute
  DashboardDokumenteIndexRoute: typeof DashboardDokumenteIndexRoute
}

const DashboardDokumenteRouteChildren: DashboardDokumenteRouteChildren = {
  DashboardDokumenteObjektIdRoute: DashboardDokumenteObjektIdRoute,
  DashboardDokumenteIndexRoute: DashboardDokumenteIndexRoute,
}

const DashboardDokumenteRouteWithChildren =
  DashboardDokumenteRoute._addFileChildren(DashboardDokumenteRouteChildren)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAufgabenRoute: typeof DashboardAufgabenRoute
  DashboardDokumenteRoute: typeof DashboardDokumenteRouteWithChildren
  DashboardFinanzierungRoute: typeof DashboardFinanzierungRoute
  DashboardHandwerkerRoute: typeof DashboardHandwerkerRoute
  DashboardMaengelRoute: typeof DashboardMaengelRoute
  DashboardMietanpassungRoute: typeof DashboardMietanpassungRoute
  DashboardMieterportalRoute: typeof DashboardMieterportalRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardPreiseRoute: typeof DashboardPreiseRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardMieteEingaengeRoute: typeof DashboardMieteEingaengeRoute
  DashboardNebenkostenIdRoute: typeof DashboardNebenkostenIdRoute
  DashboardObjekteIdRoute: typeof DashboardObjekteIdRoute
  DashboardUebergabeIdRoute: typeof DashboardUebergabeIdRoute
  DashboardMieteIndexRoute: typeof DashboardMieteIndexRoute
  DashboardNebenkostenIndexRoute: typeof DashboardNebenkostenIndexRoute
  DashboardObjekteIndexRoute: typeof DashboardObjekteIndexRoute
  DashboardUebergabeIndexRoute: typeof DashboardUebergabeIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAufgabenRoute: DashboardAufgabenRoute,
  DashboardDokumenteRoute: DashboardDokumenteRouteWithChildren,
  DashboardFinanzierungRoute: DashboardFinanzierungRoute,
  DashboardHandwerkerRoute: DashboardHandwerkerRoute,
  DashboardMaengelRoute: DashboardMaengelRoute,
  DashboardMietanpassungRoute: DashboardMietanpassungRoute,
  DashboardMieterportalRoute: DashboardMieterportalRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardPreiseRoute: DashboardPreiseRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardMieteEingaengeRoute: DashboardMieteEingaengeRoute,
  DashboardNebenkostenIdRoute: DashboardNebenkostenIdRoute,
  DashboardObjekteIdRoute: DashboardObjekteIdRoute,
  DashboardUebergabeIdRoute: DashboardUebergabeIdRoute,
  DashboardMieteIndexRoute: DashboardMieteIndexRoute,
  DashboardNebenkostenIndexRoute: DashboardNebenkostenIndexRoute,
  DashboardObjekteIndexRoute: DashboardObjekteIndexRoute,
  DashboardUebergabeIndexRoute: DashboardUebergabeIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  AvvRoute: AvvRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DatenschutzRoute: DatenschutzRoute,
  EmailBestaetigtRoute: EmailBestaetigtRoute,
  ImpressumRoute: ImpressumRoute,
  KuendigenRoute: KuendigenRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
